[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "."

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_VERSION = "9.9.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:;"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]

[functions.environment]
  OPENAI_API_KEY = ""

# Environment variables for demo mode
[context.production.environment]
  VITE_CLERK_PUBLISHABLE_KEY = ""
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_ANON_KEY = ""
  VITE_STRIPE_PUBLISHABLE_KEY = ""
  OPENAI_API_KEY = ""